### ISSUE TITLE
misp.py line 110 "KeyError: Event

### ISSUE THREAD

**Issue by icepaule** [xme/cuckoo#2]
Hello Xavier,

have you tryied using the files with MISP 2.x already?
Just to avoid me debugging while it's not intended to work.  ;-)

2018-08-09 17:40:03,731 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MISP
Traceback (most recent call last):
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 614, in process
    current.run(self.results)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/reporting/misp.py", line 110, in run
KeyError: 'Event'

Cheers
Marcus

**Comment by xme** [comment]
Hi Marcus,
When I developed the module, it was already MISP 2.x, let me try to reproduce the error...

**Comment by xme** [comment]
It looks to be ok here, I tested in both direction. Events are being created in MISP and existing IOC's are checked in MISP and injected in the Cuckoo report. My MISP version is 2.4.93.
